language: php

php:
  - 5.6

sudo: false

install:
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-source

before_script: git reset --hard HEAD

script: vendor/bin/phpunit && ./vendor/bin/test-reporter
